# We can't remove volumes in a compose override, for the test configuration using the final containers
# we don't want the volumes so this is the default override file to add the volumes in the dev case
# any override will need to include these volumes to use them.
# see:  https://github.com/docker/compose/issues/3729
---
x-nautobot-base: &nautobot-base
  volumes:
    - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
    - "../:/source"

version: "3.4"
services:
  nautobot:
    healthcheck:
      disable: true
    command: "nautobot-server runserver 0.0.0.0:8080"
    <<: *nautobot-base
  celery_worker:
    <<: *nautobot-base
  worker:
    <<: *nautobot-base
