# Generated by Django 3.1.10 on 2021-05-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_circuit_maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsource",
            name="source_type",
            field=models.CharField(blank=True, default="imap", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="rawnotification",
            name="source",
            field=models.CharField(blank=True, default="imap", max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="notificationsource",
            unique_together={("source_id", "url")},
        ),
    ]
