# Generated by Django 3.1.10 on 2021-05-28 06:28

from django.db import migrations, models
import nautobot_circuit_maintenance.fields


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_circuit_maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsource",
            name="url",
            field=nautobot_circuit_maintenance.fields.CustomURLField(),
        ),
        migrations.AlterField(
            model_name="rawnotification",
            name="source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="notificationsource",
            unique_together={("source_id", "url")},
        ),
        migrations.RemoveField(
            model_name="notificationsource",
            name="source_type",
        ),
    ]
