# Generated by Django 3.1.10 on 2021-05-31 04:26

from django.db import migrations, models
import nautobot_circuit_maintenance.fields


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_circuit_maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationsource",
            options={"ordering": ["account"]},
        ),
        migrations.AddField(
            model_name="notificationsource",
            name="account",
            field=models.EmailField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notificationsource",
            name="url",
            field=nautobot_circuit_maintenance.fields.CustomURLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="rawnotification",
            name="source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="notificationsource",
            unique_together={("account", "url")},
        ),
        migrations.RemoveField(
            model_name="notificationsource",
            name="source_id",
        ),
        migrations.RemoveField(
            model_name="notificationsource",
            name="source_type",
        ),
    ]
