# Generated by Django 3.1.10 on 2021-05-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_circuit_maintenance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationsource",
            old_name="url",
            new_name="server",
        ),
        migrations.AddField(
            model_name="notificationsource",
            name="port",
            field=models.IntegerField(blank=True, default=993, null=True),
        ),
        migrations.AlterField(
            model_name="notificationsource",
            name="source_type",
            field=models.CharField(blank=True, default="imap", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="rawnotification",
            name="source",
            field=models.CharField(blank=True, default="imap", max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="notificationsource",
            unique_together={("source_id", "server", "port")},
        ),
    ]
