# Generated by Django 3.1.10 on 2021-06-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_circuit_maintenance", "0003_improve_rawnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsource",
            name="auth_status",
            field=models.CharField(blank=True, default="UNKNOWN", editable=False, max_length=50, null=True),
        ),
    ]
