# Generated by Django 3.1.10 on 2021-07-05 10:32

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_circuit_maintenance", "0004_raw_md5"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsource",
            name="_token",
            field=django_cryptography.fields.encrypt(models.BinaryField(blank=True)),
        ),
    ]
