# Generated by Django 3.1.10 on 2021-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_circuit_maintenance", "0004_raw_md5"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsource",
            name="_token",
            field=models.BinaryField(blank=True),
        ),
    ]
