# Generated by Django 3.1.13 on 2021-11-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_circuit_maintenance", "0010_rawnotification_stamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawnotification",
            name="raw",
            field=models.BinaryField(max_length=16384),
        ),
    ]
