# Generated by Django 4.2.16 on 2024-09-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_circuit_maintenance', '0014_migrate_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
